# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#101318"

# Main text color
theme[main_fg]="#EAEFF5"

# Title color for boxes
theme[title]="#EAEFF5"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#E37B66"

# Background color of selected item in processes box
theme[selected_bg]="#3A3F4C"

# Foreground color of selected item in processes box
theme[selected_fg]="#EAEFF5"

# Color of inactive/disabled text
theme[inactive_fg]="#98A0AE"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#C6CED8"

# Background color of the percentage meters
theme[meter_bg]="#252B35"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#C6CED8"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#79A9A7" #Mauve
theme[mem_box]="#8BBE8F" #Green
theme[net_box]="#E37B66" #Maroon
theme[proc_box]="#8EABC4" #Blue

# Box divider line and small boxes line color
theme[div_line]="#606369"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="#8BBE8F"
theme[temp_mid]="#F0B87A"
theme[temp_end]="#E06C55"

# CPU graph colors (Teal -> Lavender)
theme[cpu_start]="#5F8582"
theme[cpu_mid]="#79A9A7"
theme[cpu_end]="#8FC8C3"

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]="#755E78"
theme[free_mid]="#B193B5"
theme[free_end]="#8EABC4"

# Mem/Disk cached meter (Sapphire -> Lavender)
theme[cached_start]="#526D84"
theme[cached_mid]="#6F8DAA"
theme[cached_end]="#8EABC4"

# Mem/Disk available meter (Peach -> Red)
theme[available_start]="#C88D62"
theme[available_mid]="#CB6F5A"
theme[available_end]="#E06C55"

# Mem/Disk used meter (Green -> Sky)
theme[used_start]="#587D65"
theme[used_mid]="#6F9D81"
theme[used_end]="#79A9A7"

# Download graph colors (Peach -> Red)
theme[download_start]="#C88D62"
theme[download_mid]="#CB6F5A"
theme[download_end]="#E06C55"

# Upload graph colors (Green -> Sky)
theme[upload_start]="#587D65"
theme[upload_mid]="#6F9D81"
theme[upload_end]="#79A9A7"

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Mauve)
theme[process_start]="#526D84"
theme[process_mid]="#8EABC4"
theme[process_end]="#B193B5"
