pragma Singleton

import QtQuick
import Caelestia.I18n
import qs.services
import qs.utils

Searcher {
    id: root

    list: Colours.source === "dynamic" && Colours.provider === "aether"
        ? entries.filter(entry => entry.control !== "dynamic-mode")
        : entries
    useFuzzy: true
    keys: ["label", "description", "breadcrumb", "keywords"]
    weights: [4, 2, 1, 1]

    function setting(label: string, description: string, breadcrumb: string, icon: string, pageIndex: int, subPagePath: list<int>, keywords = "", control = ""): var {
        return { label, description, breadcrumb, icon, pageIndex, subPagePath, keywords, control };
    }

    readonly property var entries: [
        setting(Tr.tr("Wallpaper & Style"), Tr.tr("Wallpaper, fonts, colours"), Tr.tr("Wallpaper & Style"), "palette", 0, [], "appearance theme"),
        setting(Tr.tr("Display wallpaper"), Tr.tr("Show the wallpaper behind the shell"), Tr.tr("Wallpaper & Style"), "wallpaper", 0, [], "background"),
        setting(Tr.tr("Transparency"), Tr.tr("Adjust shell transparency"), Tr.tr("Wallpaper & Style"), "opacity", 0, [], "opacity"),
        setting(Tr.tr("Dark theme"), Tr.tr("Use the dark colour scheme"), Tr.tr("Wallpaper & Style"), "dark_mode", 0, [], "light mode", "dynamic-mode"),
        setting(Tr.tr("Wallpapers"), Tr.tr("Choose a wallpaper"), Tr.tr("Wallpaper & Style"), "wallpaper", 0, [1], "background"),
        setting(Tr.tr("Colours"), Tr.tr("Choose shell colours"), Tr.tr("Wallpaper & Style"), "palette", 0, [3], "color theme"),
        setting(Tr.tr("Desktop widgets"), Tr.tr("Configure the desktop clock and audio visualiser"), Tr.tr("Wallpaper & Style"), "widgets", 0, [4], "background clock visualiser visualizer"),
        setting(Tr.tr("Desktop clock"), Tr.tr("Show and style the desktop clock"), Tr.tr("Wallpaper & Style › Desktop widgets"), "schedule", 0, [4], "clock"),
        setting(Tr.tr("Clock position"), Tr.tr("Choose where the desktop clock appears"), Tr.tr("Wallpaper & Style › Desktop widgets"), "open_with", 0, [4], "clock position"),
        setting(Tr.tr("Clock scale"), Tr.tr("Adjust the desktop clock size"), Tr.tr("Wallpaper & Style › Desktop widgets"), "zoom_in", 0, [4], "clock size"),
        setting(Tr.tr("Invert clock colours"), Tr.tr("Swap the desktop clock colour set"), Tr.tr("Wallpaper & Style › Desktop widgets"), "invert_colors", 0, [4], "clock colour color"),
        setting(Tr.tr("Clock background"), Tr.tr("Show a background behind the desktop clock"), Tr.tr("Wallpaper & Style › Desktop widgets"), "fill_color", 0, [4], "clock"),
        setting(Tr.tr("Clock background blur"), Tr.tr("Blur the wallpaper behind the desktop clock"), Tr.tr("Wallpaper & Style › Desktop widgets"), "blur_on", 0, [4], "clock"),
        setting(Tr.tr("Clock background opacity"), Tr.tr("Adjust desktop clock background opacity"), Tr.tr("Wallpaper & Style › Desktop widgets"), "opacity", 0, [4], "clock"),
        setting(Tr.tr("Clock shadow"), Tr.tr("Show a shadow around the desktop clock"), Tr.tr("Wallpaper & Style › Desktop widgets"), "shadow", 0, [4], "clock"),
        setting(Tr.tr("Clock shadow blur"), Tr.tr("Adjust desktop clock shadow blur"), Tr.tr("Wallpaper & Style › Desktop widgets"), "blur_on", 0, [4], "clock"),
        setting(Tr.tr("Clock shadow opacity"), Tr.tr("Adjust desktop clock shadow opacity"), Tr.tr("Wallpaper & Style › Desktop widgets"), "opacity", 0, [4], "clock"),
        setting(Tr.tr("Audio visualiser"), Tr.tr("Show and style the audio visualiser"), Tr.tr("Wallpaper & Style › Desktop widgets"), "graphic_eq", 0, [4], "visualizer visualiser audio"),
        setting(Tr.tr("Visualiser auto-hide"), Tr.tr("Hide the audio visualiser behind tiled windows"), Tr.tr("Wallpaper & Style › Desktop widgets"), "visibility", 0, [4], "visualizer visualiser"),
        setting(Tr.tr("Visualiser blur"), Tr.tr("Blur the wallpaper behind the audio visualiser"), Tr.tr("Wallpaper & Style › Desktop widgets"), "blur_on", 0, [4], "visualizer visualiser"),
        setting(Tr.tr("Visualiser rounding"), Tr.tr("Adjust audio visualiser bar rounding"), Tr.tr("Wallpaper & Style › Desktop widgets"), "rounded_corner", 0, [4], "visualizer visualiser"),
        setting(Tr.tr("Visualiser spacing"), Tr.tr("Adjust audio visualiser bar spacing"), Tr.tr("Wallpaper & Style › Desktop widgets"), "space_bar", 0, [4], "visualizer visualiser"),

        setting(Tr.tr("Network"), Tr.tr("Wi-Fi, ethernet, VPN"), Tr.tr("Network"), "wifi", 1, [], "connectivity internet"),
        setting(Tr.tr("Show all networks"), Tr.tr("Browse available Wi-Fi networks"), Tr.tr("Network"), "wifi", 1, [5], "wireless"),
        setting(Tr.tr("Saved networks"), Tr.tr("Manage saved Wi-Fi networks"), Tr.tr("Network"), "wifi", 1, [6], "wireless"),
        setting(Tr.tr("Add network"), Tr.tr("Connect to a hidden network"), Tr.tr("Network"), "add", 1, [2], "wifi wireless"),
        setting(Tr.tr("Add provider"), Tr.tr("Add a VPN provider"), Tr.tr("Network"), "vpn_key", 1, [4], "vpn"),
        setting(Tr.tr("Connected Devices"), Tr.tr("Bluetooth, pairing"), Tr.tr("Connected Devices"), "devices_other", 2, [], "bluetooth"),
        setting(Tr.tr("Pair new device"), Tr.tr("Pair a Bluetooth device"), Tr.tr("Connected Devices"), "bluetooth", 2, [2], "bluetooth"),
        setting(Tr.tr("Discoverable"), Tr.tr("Allow nearby devices to find this one"), Tr.tr("Connected Devices"), "visibility", 2, [], "bluetooth"),
        setting(Tr.tr("Pairable"), Tr.tr("Allow nearby devices to pair with this one"), Tr.tr("Connected Devices"), "visibility", 2, [], "bluetooth"),
        setting(Tr.tr("Audio"), Tr.tr("App volumes, sound devices"), Tr.tr("Audio"), "volume_up", 3, [], "sound microphone output input"),
        setting(Tr.tr("App volumes"), Tr.tr("Manage volume for playing apps"), Tr.tr("Audio"), "volume_up", 3, [1], "sound"),

        setting(Tr.tr("Panels"), Tr.tr("Dashboard, taskbar, launcher, sidebar"), Tr.tr("Panels"), "dock_to_bottom", 4, [], "shell"),
        setting(Tr.tr("Dashboard"), Tr.tr("Configure the dashboard panel"), Tr.tr("Panels"), "dashboard", 4, [1], "panel"),
        setting(Tr.tr("Taskbar"), Tr.tr("Configure the taskbar"), Tr.tr("Panels"), "dock_to_bottom", 4, [2], "bar panel"),
        setting(Tr.tr("Launcher"), Tr.tr("Configure the launcher"), Tr.tr("Panels"), "apps", 4, [3], "panel"),
        setting(Tr.tr("Sidebar"), Tr.tr("Configure the sidebar"), Tr.tr("Panels"), "side_navigation", 4, [4], "panel"),
        setting(Tr.tr("Utilities"), Tr.tr("Configure the utilities panel"), Tr.tr("Panels"), "widgets", 4, [5], "panel"),
        setting(Tr.tr("Persistent"), Tr.tr("Keep the bar visible at all times"), Tr.tr("Panels › Taskbar"), "visibility", 4, [2], "taskbar bar always visible"),
        setting(Tr.tr("Show on hover"), Tr.tr("Reveal the bar when the cursor reaches the screen edge"), Tr.tr("Panels › Taskbar"), "visibility", 4, [2], "taskbar bar reveal"),
        setting(Tr.tr("Drag threshold"), Tr.tr("Pixels dragged before the bar reveals"), Tr.tr("Panels › Taskbar"), "drag_handle", 4, [2], "taskbar bar gesture"),
        setting(Tr.tr("Workspaces"), Tr.tr("Indicators, window icons"), Tr.tr("Panels › Taskbar"), "workspaces", 4, [2, 6], "workspace"),
        setting(Tr.tr("Workspace icons"), Tr.tr("Choose how workspace indicators are displayed"), Tr.tr("Panels › Taskbar › Workspaces"), "workspaces", 4, [2, 6], "default simple numbered active window style"),
        setting(Tr.trCtx("Shown", "number of workspaces"), Tr.tr("Number of workspaces displayed"), Tr.tr("Panels › Taskbar › Workspaces"), "workspaces", 4, [2, 6], "workspace count"),
        setting(Tr.tr("Active indicator"), Tr.tr("Show the active workspace indicator"), Tr.tr("Panels › Taskbar › Workspaces"), "workspaces", 4, [2, 6]),
        setting(Tr.tr("Active trail"), Tr.tr("Show the active workspace trail"), Tr.tr("Panels › Taskbar › Workspaces"), "workspaces", 4, [2, 6]),
        setting(Tr.tr("Occupied background"), Tr.tr("Show occupied workspace backgrounds"), Tr.tr("Panels › Taskbar › Workspaces"), "workspaces", 4, [2, 6]),
        setting(Tr.tr("Show windows"), Tr.tr("Show icons of open windows on each workspace"), Tr.tr("Panels › Taskbar › Workspaces"), "window", 4, [2, 6], "workspace icons"),
        setting(Tr.tr("Max window icons"), Tr.tr("Maximum icons on each workspace"), Tr.tr("Panels › Taskbar › Workspaces"), "window", 4, [2, 6]),
        setting(Tr.tr("Per-monitor workspaces"), Tr.tr("Show each monitor's workspaces independently"), Tr.tr("Panels › Taskbar › Workspaces"), "monitor", 4, [2, 6]),
        setting(Tr.tr("Active window"), Tr.tr("Title display, popout"), Tr.tr("Panels › Taskbar"), "web_asset", 4, [2, 7]),
        setting(Tr.tr("Tray"), Tr.tr("System tray icons"), Tr.tr("Panels › Taskbar"), "widgets", 4, [2, 8]),
        setting(Tr.tr("Status icons"), Tr.tr("Visible indicators"), Tr.tr("Panels › Taskbar"), "signal_cellular_alt", 4, [2, 9]),
        setting(Tr.tr("Clock"), Tr.tr("Date, icon, background"), Tr.tr("Panels › Taskbar"), "schedule", 4, [2, 10]),
        setting(Tr.trCtx("Compact", "taskbar active window layout"), Tr.tr("Use a compact active-window layout"), Tr.tr("Panels › Taskbar › Active window"), "web_asset", 4, [2, 7]),
        setting(Tr.trCtx("Inverted", "taskbar active window: swap the title and class order"), Tr.tr("Swap the active-window title and class order"), Tr.tr("Panels › Taskbar › Active window"), "swap_vert", 4, [2, 7]),
        setting(Tr.tr("Show on hover"), Tr.tr("Only show the active window title while hovering"), Tr.tr("Panels › Taskbar › Active window"), "visibility", 4, [2, 7], "active window"),
        setting(Tr.tr("Popout on hover"), Tr.tr("Show a window details popout when hovering"), Tr.tr("Panels › Taskbar › Active window"), "visibility", 4, [2, 7], "active window"),
        setting(Tr.trCtx("Background", "taskbar tray: draw a background behind the tray"), Tr.tr("Draw a background behind the tray"), Tr.tr("Panels › Taskbar › Tray"), "widgets", 4, [2, 8]),
        setting(Tr.tr("Recolour icons"), Tr.tr("Recolour system tray icons"), Tr.tr("Panels › Taskbar › Tray"), "palette", 4, [2, 8], "tray"),
        setting(Tr.trCtx("Compact", "taskbar tray layout"), Tr.tr("Use a compact taskbar tray layout"), Tr.tr("Panels › Taskbar › Tray"), "widgets", 4, [2, 8]),
        setting(Tr.tr("Popout on hover"), Tr.tr("Show the tray menu popout when hovering"), Tr.tr("Panels › Taskbar › Tray"), "visibility", 4, [2, 8], "tray"),
        setting(Tr.tr("Visible icons"), Tr.tr("Choose visible status icons"), Tr.tr("Panels › Taskbar › Status icons"), "signal_cellular_alt", 4, [2, 9], "status"),
        setting(Tr.tr("Popout on hover"), Tr.tr("Show a details popout when hovering the status icons"), Tr.tr("Panels › Taskbar › Status icons"), "visibility", 4, [2, 9], "status"),
        setting(Tr.trCtx("Background", "taskbar clock: draw a background behind the clock"), Tr.tr("Draw the clock background"), Tr.tr("Panels › Taskbar › Clock"), "schedule", 4, [2, 10]),
        setting(Tr.tr("Show date"), Tr.tr("Show the date in the taskbar clock"), Tr.tr("Panels › Taskbar › Clock"), "calendar_today", 4, [2, 10]),
        setting(Tr.tr("Show icon"), Tr.tr("Show the clock icon"), Tr.tr("Panels › Taskbar › Clock"), "schedule", 4, [2, 10]),
        setting(Tr.tr("Show seconds"), Tr.tr("Show seconds in the taskbar clock"), Tr.tr("Panels › Taskbar › Clock"), "schedule", 4, [2, 10]),
        setting(Tr.tr("Scroll actions"), Tr.tr("Configure workspace, volume and brightness scrolling"), Tr.tr("Panels › Taskbar"), "swap_vert", 4, [2], "scroll"),
        setting(Tr.tr("Enabled"), Tr.tr("Show the dashboard panel"), Tr.tr("Panels › Dashboard"), "toggle_on", 4, [1], "dashboard"),
        setting(Tr.tr("Show on hover"), Tr.tr("Reveal when the cursor reaches the screen edge"), Tr.tr("Panels › Dashboard"), "visibility", 4, [1], "dashboard"),
        setting(Tr.tr("Show clock seconds"), Tr.tr("Display seconds for the clock in the main panel"), Tr.tr("Panels › Dashboard"), "schedule", 4, [1]),
        setting(Tr.tr("Tabs"), Tr.tr("Choose dashboard tabs"), Tr.tr("Panels › Dashboard"), "tab", 4, [1], "media performance weather"),
        setting(Tr.tr("Performance widgets"), Tr.tr("Choose dashboard performance widgets"), Tr.tr("Panels › Dashboard"), "monitoring", 4, [1], "battery cpu gpu memory storage network"),
        setting(Tr.tr("Drag threshold"), Tr.tr("Pixels dragged before the dashboard opens"), Tr.tr("Panels › Dashboard"), "drag_handle", 4, [1], "gesture"),
        setting(Tr.tr("Enabled"), Tr.tr("Show the launcher panel"), Tr.tr("Panels › Launcher"), "toggle_on", 4, [3], "launcher"),
        setting(Tr.tr("Action prefix"), Tr.tr("Prefix used to run actions in the launcher"), Tr.tr("Panels › Launcher"), "terminal", 4, [3], "command"),
        setting(Tr.tr("Fuzzy search"), Tr.tr("Configure launcher fuzzy search categories"), Tr.tr("Panels › Launcher"), "search", 4, [3], "launcher"),
        setting(Tr.tr("Max items shown"), Tr.tr("Maximum launcher results"), Tr.tr("Panels › Launcher"), "format_list_numbered", 4, [3], "launcher"),
        setting(Tr.tr("Max wallpapers"), Tr.tr("Maximum wallpaper results"), Tr.tr("Panels › Launcher"), "wallpaper", 4, [3], "launcher"),
        setting(Tr.tr("Drag threshold"), Tr.tr("Pixels dragged before the launcher opens"), Tr.tr("Panels › Launcher"), "drag_handle", 4, [3], "gesture"),
        setting(Tr.tr("Vim keybinds"), Tr.tr("Navigate results with Ctrl+hjkl"), Tr.tr("Panels › Launcher"), "keyboard", 4, [3]),
        setting(Tr.tr("Enable dangerous actions"), Tr.tr("Allow actions that shut down or log out"), Tr.tr("Panels › Launcher"), "warning", 4, [3]),
        setting(Tr.tr("Enabled"), Tr.tr("Show the sidebar panel"), Tr.tr("Panels › Sidebar"), "toggle_on", 4, [4], "sidebar"),
        setting(Tr.tr("Drag threshold"), Tr.tr("Pixels dragged before the sidebar opens"), Tr.tr("Panels › Sidebar"), "drag_handle", 4, [4], "gesture"),
        setting(Tr.tr("Enabled"), Tr.tr("Show the utilities panel"), Tr.tr("Panels › Utilities"), "toggle_on", 4, [5], "utilities"),
        setting(Tr.tr("Keep awake"), Tr.tr("Show the idle lock toggle"), Tr.tr("Panels › Utilities"), "visibility", 4, [5], "idle"),
        setting(Tr.tr("Nightlight"), Tr.tr("Toggle nightlight"), Tr.tr("Panels › Utilities"), "nightlight", 4, [5]),
        setting(Tr.tr("Do not disturb"), Tr.tr("Silence notifications"), Tr.tr("Panels › Utilities"), "notifications_off", 4, [5], "dnd"),
        setting(Tr.tr("Screen recorder"), Tr.tr("Show the screen recorder card"), Tr.tr("Panels › Utilities"), "videocam", 4, [5]),
        setting(Tr.tr("Quick toggles"), Tr.tr("Show the quick toggles card"), Tr.tr("Panels › Utilities"), "toggle_on", 4, [5]),
        setting(Tr.tr("Wi-Fi"), Tr.tr("Toggle wireless networking"), Tr.tr("Panels › Utilities"), "wifi", 4, [5]),
        setting(Tr.tr("Bluetooth"), Tr.tr("Toggle the Bluetooth adapter"), Tr.tr("Panels › Utilities"), "bluetooth", 4, [5]),
        setting(Tr.tr("Microphone"), Tr.tr("Mute or unmute the default source"), Tr.tr("Panels › Utilities"), "mic", 4, [5]),
        setting(Tr.tr("VPN"), Tr.tr("Connect or disconnect the VPN"), Tr.tr("Panels › Utilities"), "vpn_key", 4, [5]),

        setting(Tr.tr("Apps"), Tr.tr("Default apps, favourites, hidden apps"), Tr.tr("Apps"), "apps", 5, [], "applications"),
        setting(Tr.tr("Default applications"), Tr.tr("Choose default terminal, audio, media and file manager apps"), Tr.tr("Apps"), "apps", 5, [], "defaults"),
        setting(Tr.tr("All apps"), Tr.tr("Browse installed apps, set favourites and hidden"), Tr.tr("Apps"), "apps", 5, [1], "applications library"),
        setting(Tr.tr("Services"), Tr.tr("Poll intervals, lyrics backend"), Tr.tr("Services"), "build", 6, [], "system"),
        setting(Tr.tr("Notifications"), Tr.tr("Notifications, toasts, timeouts"), Tr.tr("Services"), "notifications", 6, [1], "notification"),
        setting(Tr.tr("Show in fullscreen"), Tr.tr("Whether notifications appear over fullscreen apps"), Tr.tr("Services › Notifications"), "notifications", 6, [1], "notification fullscreen"),
        setting(Tr.tr("Expire automatically"), Tr.tr("Dismiss notifications after their timeout"), Tr.tr("Services › Notifications"), "timer", 6, [1]),
        setting(Tr.tr("Open expanded"), Tr.tr("Show notifications expanded by default"), Tr.tr("Services › Notifications"), "unfold_more", 6, [1]),
        setting(Tr.tr("Default timeout"), Tr.tr("Time before a notification dismisses"), Tr.tr("Services › Notifications"), "timer", 6, [1]),
        setting(Tr.tr("Group preview count"), Tr.tr("Notifications shown per group before collapsing"), Tr.tr("Services › Notifications"), "format_list_numbered", 6, [1]),
        setting(Tr.tr("Visible toasts"), Tr.tr("Maximum number of toasts shown at once"), Tr.tr("Services › Notifications"), "notifications", 6, [1]),
        setting(Tr.tr("Toast events"), Tr.tr("Choose notification events that show toasts"), Tr.tr("Services › Notifications"), "notifications", 6, [1], "charging game mode dnd audio vpn now playing"),
        setting(Tr.tr("Media refresh"), Tr.tr("How often the media position updates"), Tr.tr("Services"), "refresh", 6, [], "poll interval"),
        setting(Tr.tr("System stats refresh"), Tr.tr("CPU, memory and GPU update interval"), Tr.tr("Services"), "refresh", 6, [], "poll interval"),
        setting(Tr.tr("Wi-Fi rescan"), Tr.tr("How often available networks are rescanned"), Tr.tr("Services"), "wifi", 6, [], "poll interval"),
        setting(Tr.tr("Lyrics backend"), Tr.tr("Source used to fetch synced lyrics"), Tr.tr("Services"), "lyrics", 6, [], "media"),
        setting(Tr.tr("Volume step"), Tr.tr("Amount the volume changes per scroll"), Tr.tr("Services"), "volume_up", 6, [], "sound"),
        setting(Tr.tr("Brightness step"), Tr.tr("Amount the brightness changes per scroll"), Tr.tr("Services"), "brightness_6", 6, [], "display"),
        setting(Tr.tr("Language & Region"), Tr.tr("UI language, weather location, display units"), Tr.tr("Language & Region"), "globe", 7, [], "locale"),
        setting(Tr.tr("UI language"), Tr.tr("The language used in the shell UI"), Tr.tr("Language & Region"), "translate", 7, [], "locale"),
        setting(Tr.tr("Temperature"), Tr.tr("Units for weather temperatures"), Tr.tr("Language & Region"), "device_thermostat", 7, [], "units weather"),
        setting(Tr.tr("System temperatures"), Tr.tr("Units for CPU and GPU temperatures"), Tr.tr("Language & Region"), "device_thermostat", 7, [], "units cpu gpu"),
        setting(Tr.tr("Data sizes"), Tr.tr("Units for data sizes and network speeds"), Tr.tr("Language & Region"), "data_usage", 7, [], "units network"),
        setting(Tr.tr("Clock format"), Tr.tr("How times are shown across the shell"), Tr.tr("Language & Region"), "schedule", 7, [], "time 12 24 hour"),
        setting(Tr.tr("About"), Tr.tr("System information, credits"), Tr.tr("About"), "info", 8, [], "version system")
    ]
}
