hl.config({
    plugin = {
        hymission = {
            niri_mode = 0,
            niri_workspace_scale = 1.0,
            only_active_workspace = 1,
            only_active_monitor = 1,
            workspace_strip_anchor = "left",
            workspace_strip_empty_mode = "existing",
            workspace_strip_thickness = 160,
            workspace_strip_gap = 24,
            workspace_strip_label_font_size = 22,
            workspace_strip_label_opacity = 0.6,
            layout_engine = grid,
            hide_bar_when_strip = 1,
            hide_layers_when_overview = 1,
            hide_overview_layer_namespaces = "chromack,wardnc,wardbnc,dashboard",
            close_special_workspaces_on_open = 1,
            toggle_switch_mode = 0,
            switch_toggle_auto_next = 0,
            switch_release_key = Super_L,
            one_workspace_per_row = 0,
            outer_padding_bottom = 92,
            outer_padding_top = 92,
            outer_padding_left = 92,
            outer_padding_right = 92,
        },
    },
})
