hl.config({
    plugin = {
        hymission = {
            niri_mode = 1,
            niri_preview_disabled = 1,
            niri_workspace_scale = 1.0,
            niri_layout_scale = 2.0,
            niri_multi_ws_scale = 0.40,
            niri_workspace_gap = 1.0,
            niri_window_gaps = -1,
            niri_mode_show_empty_workspaces_btwn = 1,
            debug_logs = 1,
            only_active_workspace = 1,
            only_active_monitor = 1,
            workspace_strip_anchor = "left",
            workspace_strip_empty_mode = "existing",
            workspace_strip_thickness = 160,
            workspace_strip_gap = 24,
            workspace_strip_label_font_size = 22,
            workspace_strip_label_opacity = 0.7,
            layout_engine = grid,
            hide_bar_when_strip = 1,
            hide_layers_when_overview = 1,
            hide_bar_namespaces = "hypr-dock,waybar,chromack,wardnc,wardbnc,dashboard,rofi",
            hide_overview_layer_namespaces = "chromack,wardnc,wardbnc,dashboard,rofi",
            close_special_workspaces_on_open = 1,
            expand_selected_window = 1,
            multi_workspace_expand_selected_window = 1,
            refresh_previews_on_config_reload = 1,
            toggle_switch_mode = 0,
            switch_toggle_auto_next = 0,
            switch_release_key = Super_L,
            one_workspace_per_row = 0,
            outer_padding_bottom = 92,
            outer_padding_top = 92,
            outer_padding_left = 92,
            outer_padding_right = 92,
        },
    },
})
