require("autostart")
require("keybindings")
require("monitors")
require("decorations")
require("borders")
require("animations")
require("environment")
require("cursor")
require("windows")
require("permissions")
require("inputs")
require("plugins")
require("workspaces")
require("hypridle")
require("hyprlock")
require("hyprsunset")
require("hymission")
require("hymission-background")
require("xdph")

require("custom-layouts.grid")
require("custom-layouts.spiral")
require("custom-layouts.manual")
require("custom-layouts.niriscroll")
require("custom-layouts.centerstack")

hl.bind("SUPER + CTRL + SHIFT + O", hl.dsp.exec_cmd("~/bin/launch-terminal"))
