-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Acer Technologies KG271U N3 3511036353W01",
  mode = "2560x1440@144.01",
  position = "1920x0",
  scale = 1.25,
  vrr = 0,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:ASUSTek COMPUTER INC ASUS VG277Q1A T1LMTF101706",
  mode = "1920x1080@144.00",
  position = "0x0",
  scale = 1,
  vrr = 0,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:BOE 0x0A2D",
  disabled = true,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:Acer Technologies KG271U N3 3511036353W01", persistent = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:Acer Technologies KG271U N3 3511036353W01", persistent = true })
hl.workspace_rule({ workspace = "3", monitor = "desc:Acer Technologies KG271U N3 3511036353W01", persistent = true })
hl.workspace_rule({ workspace = "4", monitor = "desc:Acer Technologies KG271U N3 3511036353W01", persistent = true })
hl.workspace_rule({ workspace = "5", monitor = "desc:Acer Technologies KG271U N3 3511036353W01", persistent = true })
hl.workspace_rule({ workspace = "6", monitor = "desc:Acer Technologies KG271U N3 3511036353W01" })
hl.workspace_rule({ workspace = "7", monitor = "desc:Acer Technologies KG271U N3 3511036353W01" })
hl.workspace_rule({ workspace = "8", monitor = "desc:Acer Technologies KG271U N3 3511036353W01" })
hl.workspace_rule({ workspace = "9", monitor = "desc:Acer Technologies KG271U N3 3511036353W01" })
hl.workspace_rule({ workspace = "10", monitor = "desc:ASUSTek COMPUTER INC ASUS VG277Q1A T1LMTF101706", persistent = true })
hl.workspace_rule({ workspace = "11", monitor = "desc:ASUSTek COMPUTER INC ASUS VG277Q1A T1LMTF101706", persistent = true })
hl.workspace_rule({ workspace = "12", monitor = "desc:ASUSTek COMPUTER INC ASUS VG277Q1A T1LMTF101706", persistent = true })
hl.workspace_rule({ workspace = "special:aether", monitor = "desc:Acer Technologies KG271U N3 3511036353W01" })
hl.workspace_rule({ workspace = "special:discordspace", monitor = "desc:Acer Technologies KG271U N3 3511036353W01" })
hl.workspace_rule({ workspace = "special:mediaspace", monitor = "desc:Acer Technologies KG271U N3 3511036353W01" })
hl.workspace_rule({ workspace = "special:nexus", monitor = "desc:Acer Technologies KG271U N3 3511036353W01" })
hl.workspace_rule({ workspace = "special:scratchpad", monitor = "desc:Acer Technologies KG271U N3 3511036353W01" })
hl.workspace_rule({ workspace = "special:socialspace", monitor = "desc:Acer Technologies KG271U N3 3511036353W01" })
