require("autostart")
require("keybindings")
require("monitors")
require("decorations")
require("borders")
require("animations")
require("environment")
require("cursor")
require("windows")
require("permissions")
require("inputs")
require("plugins")
require("workspaces")
require("hypridle")
require("hyprlock")
require("hyprsunset")
require("xdph")

hl.bind("SUPER + ALT + CTRL + SHIFT + O", hl.dsp.exec_cmd("kitty"))
