general {
    # https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
    col.active_border = rgb(ad2222) rgb(ad2222) rgb(ad2222) rgb(ad2222) rgb(feccca) rgb(ad2222) rgb(ad2222) rgb(ad2222) rgb(ad2222) rgb(ad2222) 35deg
    col.inactive_border = rgba(2d2f33ff)
}
