general {
    # https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
    col.active_border = rgb(AE3F82) rgb(AE3F82) rgb(AE3F82) rgb(AE3F82) rgb(E39C45) rgb(AE3F82) rgb(AE3F82) rgb(AE3F82) 35deg
    col.inactive_border = rgba(725a5acc)
}
